---
title: "Activity 3 - Day 1"
output: github_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(GGally)
```

```{r}
library(tidyverse)
library(tidymodels)
library(scatterplot3d)
```

```{r}
hfi <- readr::read_csv("https://www.openintro.org/data/csv/hfi.csv")
hfi
hfi_2016 <- hfi %>% filter (year == 2016)
```

```{r}
m1 <- lm(pf_score~pf_expression_control + hf_score + ef_score, data = hfi)
tidy(m1)
```

```{r warning=FALSE}
hfi_2016 %>% 
  select(ends_with("_score")) %>% 
  ggpairs()
```

```{r}
m_hr_ef <- lm(pf_score ~ hf_score + ef_score, data = hfi_2016)
tidy(m_hr_ef)
```

```{r}
hfi_scatter_3d <- hfi_2016 %>% select(hf_score, ef_score, pf_score)
scatterplot3d(hfi_scatter_3d[,1:3], 
              pch = 15, 
              color="steelblue",
              grid = TRUE)
```

# Day 02

```{r}
# review any visual patterns
hfi %>% 
  select(pf_score, pf_expression_influence, pf_expression_control) %>% 
  ggpairs()

#fit the mlr model
m_pf <- lm(pf_score ~ pf_expression_influence + pf_expression_control, data = hfi)
tidy(m_pf)
```

```{r}
summary(m_pf)
```

```{r}
glance(m_pf)
```

```{r}
# obtain fitted values and residuals
m_pf_aug <- augment(m_pf)

# plot fitted values and residuals
ggplot(data = m_pf_aug, aes(x = .fitted, y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  xlab("Fitted values") +
  ylab("Residuals")
```

```{r}
ggplot(data = m_pf_aug, aes(x = .resid)) +
  geom_histogram(binwidth = 0.25) +
  xlab("Residuals")
```

```{r}
hfi %>%
  filter(countries == "United States" & year == 2016) %>%
  select(pf_score, pf_expression_influence, pf_expression_control)
```

```{r}
hfi %>%
  filter(countries == "United States" & year == 2016) %>%
  predict(m_pf, .)
```

